import Head from 'next/head'
import Beggining from './beggining'
import Nav from './nav'
import Skills from './skills'



export default function Home() {

  return (
    <>
      <Head>
        <title>Andrés Germain dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section  className='min-h-screen bg-black'>
        <header>
        <nav className='max-h-20'>
          <Nav/>
        </nav>
        </header>
      <main>
        <div className='text-white mt-[50%]'>
        <Beggining />
        <div className='flex mx-auto mt-[70%] w-[15%] animate-bounce'>
          <img src='./arrow.png' width={100}/>
        </div>
       </div>
       <div className='mt-[50%]'>
        <Skills />
       </div>
      </main>
      </section>
      <footer className='bg-white'>
        <h1>asdasd</h1>
      </footer>
     
    </>
  )
}
