import Head from "next/head";
import Beggining from "./beggining";
import Nav from "./nav";
import Skills from "./skills";
import Projects from "./projects";
import Cv from "./cv";
import Footer from "./footer";
import { Link, animateScroll as scroll } from "react-scroll";
import Image from "next/image";

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Andrés Germain dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portfolio.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <section className="min-h-screen bg-black font-myFont">
        <header>
          <nav className="max-h-20">
            <Nav />
          </nav>
        </header>
        <main>
          <div className="text-white mt-[50%] sm:mt-[25%] lg:mt-[12%]">
            <Beggining />
            <div className="mx-auto mt-[50%] w-[15%] animate-bounce sm:mt-[25%] lg:mt-[10%]">
              <Link
                activeClass="active"
                to="skills"
                spy={true}
                smooth={true}
                offset={-250}
                duration={500}
              >
                <Image
                width={500}
                height={500}
                alt="img not found"
                  src="/arrow.png"
                  className="w-[50%] mx-auto cursor-grab sm:w-[35%] sm:mx-auto lg:w-[20%] lg:mx-auto"
                />
              </Link>
            </div>
          </div>
          <div className="mt-[60%] text-white text-2xl lg:mt-[18%]" id="skills">
            <h2 className="text-center mb-10">SKILLS</h2>
            <Skills />
          </div>
          <div
            className="mt-[60%]  text-white font-light lg:mt-[10%]"
            id="proyectos"
          >
            <h2 className="text-center mb-10 text-2xl">PROYECTOS</h2>
            <p className="text-center mb-5 underline">
              «Desliza hacia los lados»
            </p>
            <Projects />
          </div>
          <div className="mt-[80%] lg:mt-[18%]" id="cv">
            <Cv />
          </div>
        </main>
      </section>
      <footer className="bg-black" id="contacto">
        <Footer />
      </footer>
    </div>
  );
}
