import Head from 'next/head'
import Beggining from './beggining'
import Nav from './nav'



export default function Home() {

  return (
    <>
      <Head>
        <title>Andrés Germain dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <section className='grid min-h-screen bg-black'>
        <nav className='max-h-20'>
          <Nav/>
        </nav>
        <section className='text-white h-[50%] mb-[60%]'>
        <Beggining />
        </section>
       </section>
      </main>
    </>
  )
}
